export const books = [
    { key: "1", name: "Genesis" },
    { key: "2", name: "Exodus" },
    { key: "3", name: "Leviticus" },
    { key: "4", name: "Numbers" },
    { key: "5", name: "Deuteronomy" },
    { key: "6", name: "Joshua" },
    { key: "7", name: "Judges" },
    { key: "8", name: "Ruth" },
    { key: "9", name: "1 Samuel" },
    { key: "10", name: "2 Samuel" },
    { key: "11", name: "1 Kings" },
    { key: "12", name: "2 Kings" },
    { key: "13", name: "1 Chronicles" },
    { key: "14", name: "2 Chronicles" },
    { key: "15", name: "Ezra" },
    { key: "16", name: "Nehemiah" },
    { key: "17", name: "Esther" },
    { key: "18", name: "Job" },
    { key: "19", name: "Psalms" },
    { key: "20", name: "Proverbs" },
    { key: "21", name: "Ecclesiastes" },
    { key: "22", name: "Song of Solomon" },
    { key: "23", name: "Isaiah" },
    { key: "24", name: "Jeremiah" },
    { key: "25", name: "Lamentations" },
    { key: "26", name: "Ezekiel" },
    { key: "27", name: "Daniel" },
    { key: "28", name: "Hosea" },
    { key: "29", name: "Joel" },
    { key: "30", name: "Amos" },
    { key: "31", name: "Obadiah" },
    { key: "32", name: "Jonah" },
    { key: "33", name: "Micah" },
    { key: "34", name: "Nahum" },
    { key: "35", name: "Habakkuk" },
    { key: "36", name: "Zephaniah" },
    { key: "37", name: "Haggai" },
    { key: "38", name: "Zechariah" },
    { key: "39", name: "Malachi" },
    { key: "40", name: "Matthew" },
    { key: "41", name: "Mark" },
    { key: "42", name: "Luke" },
    { key: "43", name: "John" },
    { key: "44", name: "Acts" },
    { key: "45", name: "Romans" },
    { key: "46", name: "1 Corinthians" },
    { key: "47", name: "2 Corinthians" },
    { key: "48", name: "Galatians" },
    { key: "49", name: "Ephesians" },
    { key: "50", name: "Philippians" },
    { key: "51", name: "Colossians" },
    { key: "52", name: "1 Thessalonians" },
    { key: "53", name: "2 Thessalonians" },
    { key: "54", name: "1 Timothy" },
    { key: "55", name: "2 Timothy" },
    { key: "56", name: "Titus" },
    { key: "57", name: "Philemon" },
    { key: "58", name: "Hebrews" },
    { key: "59", name: "James" },
    { key: "60", name: "1 Peter" },
    { key: "61", name: "2 Peter" },
    { key: "62", name: "1 John" },
    { key: "63", name: "2 John" },
    { key: "64", name: "3 John" },
    { key: "65", name: "Jude" },
    { key: "66", name: "Revelation" },
  ];
  